# Generated by Django 6.0 on 2025-12-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='line',
            new_name='deadline',
        ),
    ]
